package io.mobilegraph.rag

import io.mobilegraph.documents.Document
import io.mobilegraph.models.ModelOutput
import io.mobilegraph.vectorstores.ScoredDocument

/**
 * Detailed result of a RAG pipeline execution, containing the model output and debugging context.
 *
 * This class provides transparency into the RAG process by exposing the final prompt,
 * the set of retrieved documents, and the filtering results.
 *
 * @property output The final response generated by the [ChatModel].
 * @property finalPrompt The combined string (context + query) that was actually sent to the LLM.
 * @property retrievedDocs The raw list of documents found by the [Retriever] with their similarity scores.
 * @property filteredDocs The subset of [retrievedDocs] that passed the similarity threshold.
 * @property similarityThreshold The threshold value used to filter the retrieved documents.
 */
data class RagExecutionResult(
    val output: ModelOutput,
    val finalPrompt: String,
    val retrievedDocs: List<ScoredDocument> = emptyList(),
    val filteredDocs: List<Document> = emptyList(),
    val similarityThreshold: Float? = null,
)
